name = "Michael Blockless 1"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "Michael Blockless 1_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "Michael Blockless 1.wasm"
command = "npm run build:release"
